version: '3.8' 

services:
  # Frontend 
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      # Map semua file 
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
      - ./frontend/vite.config.js:/usr/src/app/vite.config.js
      - ./frontend/index.html:/usr/src/app/index.html
    depends_on:
      - backend 

  # Backend (Node.js)
  backend:
    build: ./backend 
    ports:
      - "3001:3001" # Map port 3001 di host ke 3001 di container
    volumes:
      - ./backend:/usr/src/app 
    environment:
      - DB_USER=myuser
      - DB_HOST=db # PENTING: 'db' adalah nama service database di bawah
      - DB_NAME=mydb
      - DB_PASSWORD=mypassword
      - DB_PORT=5432
    depends_on:
      - db # Pastikan database jalan dulu sebelum backend

  # Database (PostgreSQL)
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432" # (Opsional) 
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data: